title: app MonGeuleTon
description: Identifie les pltas de votre repas
about: 

  Projet de William et Sylvère

code: https://github.com/Syllaweg/MonGueuleton

sampleImages:
    - name: sushi
    url: https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg
